### ISSUE TITLE
Feature #1: User can view a holiday on the day they visit

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#1]
## ⚙️ Feature

User can view a holiday on the day they visit, or a message telling them 'All partied out today! Try a new date to see what you can look forward to!"

## 📐 Functionality

1. Calendar will appear with yesterday's date
2. Calendar will flip page, showing today's date
3. Camera will re-frame calendar while calendar moves to the upper-left
5. A celebration scene will load, a title (fetched), and a description (also fetched)

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/88114510-a2c7-459d-b178-0753485f2d89)

## ✅ Task List

- [x] Set up HTML
- [x] Set up Tailwind CSS classes
- [x] Upload necessary images/objects
- [x] Write TS
   - [x] Import threejs, GLTFLoader, and TextureLoader
   - [x] Set up variables for media breakpoint, the date, previous date, queries, and elements to be given textContent
   - [x] Create calendar scene
      - [x] Set up scene, camera, light, load model, load correct textures, and add model to scene
      - [x] Run animation
      - [x] Stop updating once the animation is complete and trigger:
         - [x] Camera movement
         - [x] Canvas repositioning/resizing
   - [x] Fetch data from API
      - [x] Try to fetch, if successful:
         - [x] Update holiday name
         - [x] Update holiday description
         - [x] Create celebration scene
            - [x] Set up scene, camera, light, load model, and add model to scene
            - [x] Render once
      - [x] If the server is reached, but the return is insufficient:
         - [x] Display 'All partied out...' message
      - [x] Catch for errors
         - [x] Display 'All partied out...' message
