### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#11]
## ✅ Task List
- [x] Remove sidebar, create header instead
- [x] Add icon
- [x] Create and import images for header
- [x] Create scale transformations for header buttons
- [ ] Create and import parade scene
- [ ] Create and import fairgrounds scene
- [ ] Add orbitcontrols
- [x] Use event delegation to control header buttons
- [x] Figure out how to reference files in such a way that github pages can find them
- [x] Favorite toggle should be its own separate function, to run within getHoliday and when going to a saved holiday
- [x] Creating a DOM representation of a SavedHoliday should be condensed into one function
- [x] loadTexture should be called as part of destructuring.
- [x] Move all things contingent on a successful getHoliday into getHoliday
- [ ] Update renderer size/position on window size change
- [ ] Write a README.md to talk about my coding experience, the trouble importing a js file in a ts file, the trouble I had when an HTMLCollection's length didn't match ]HTMLCollection].length, and better explain the difficulty I had returning the promise from the recursive function.
