### ISSUE TITLE
Feature #2: User can search for holidays for different days

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#2]
## ⚙️ Feature

User can search for holidays for different days

## 📐 Functionality

1. User can click a 'new' (plus icon) button on a sidebar that allows them to check other days.
2. User can click a 'search' button once they've updated the date input element.
3. Display updates appropriately

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/30e69aca-5237-4334-9b89-6a23783fafd7)

## ✅ Task List

- [x] Create the sidebar and dialog pop-up w/ input and submit in HTML
- [x] Add CSS classes via tailwind for styling
- [x] Add JS to open the form
- [x] Add JS to listen for form submission and then store the input into the correct variables (and reset and close the dialog)
- [x] Add JS to flip the calendar page 
- [x] Add JS to handle celebration display (recreate the display as a foundation for future development when multiple celebration scenes will exist; don't simply toggle between holiday found and not found states)
