### ISSUE TITLE
Feature #3: User can save their favorite holidays

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#3]
## ⚙️ Feature

User can save their favorite holidays

## 📐 Functionality

1. Users can click the floppy disk button on the sidebar to create a local copy of the holiday
2. Users can click a star button to 'favorite' and save the holiday
3. In either case, a notification saying 'Saved!' will pop up briefly.

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/8517dd9b-03ca-4057-b99b-372d4d76c804)

## ✅ Task List

- [x] Add HTML/CSS for 'Save!' notification and favorite star icon.
- [x] Save an identifier for the celebration glb that loads to a variable.
- [x] Create event handlers, visible effects, for floppy disk/star
- [x] Build a holiday object, stringify it, and setItem it into local storage.
