### ISSUE TITLE
Feature #4: User can view saved holidays

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#4]
## ⚙️ Feature

User can view their favorite holidays

## 📐 Functionality

1. By clicking the folder icon, user can pull up a gui of their saved holidays
2. By clicking the 'x' in the upper left, user can close the gui

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/ed033e0d-3fea-4305-87fe-68fb8225c154)

## ✅ Task List

- [x] Build HTML/CSS for displaying holidays (a dialog element)
- [x] Open dialog on click of the folder icon (add event listener, write function to handle that)
- [x] Close dialog on click of the 'x'
- [x] Construct DOM elements for each SavedHoliday and add them to an array
- [x] Sort the array by whether or not a holiday is favorited, and then by day of the year
- [x] Add each element of the array to the dialog
- [x] Add a default message to display when no holidays are saved
- [x] When storing new holiday (including new level of favorited to an otherwise unchanged holiday), update the open dialog
- [x] When user clicks on a saved holiday, it should pull that holiday up, meaning:
   - [x] the calendar should flip
   - [x] the object/name/desc should load
- [x] Whenever a holiday is loaded, it should check the data for a match and ensure the favorite status of the loaded holiday matches if a match is found.
