### ISSUE TITLE
Feature #5: User can remove their favorite holidays

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/front-end-project#5]
## ⚙️ Feature

User can remove their saved holidays

## 📐 Functionality

1. User can click the trash icon on a saved holiday to create a confirmation prompt.
2. User can click the check icon on the confirmation prompt to remove the holiday from data and from the DOM
3. User can click the 'x' icon on the confirmation prompt to close the confirmation prompt

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/13effa10-da62-446e-b066-3c30fa701f06)

## ✅ Task List

- [x] Create confirmation prompt with HTML/CSS
- [x] Create functionality for prompt
- [x] Create functionality for confirm
- [x] Create functionality for cancel
